const defaults = {
  layoutControls: {
    primaryColor: false,
    posterImage: false,
    posterImageSize: 'contain',
    playButtonShowing: true,
    playPauseAnimation: true,
    fillToContainer: false,
    autoPlay: {
      active: false,
      waitInteraction: false,
    },
    mute: false,
    loop: false,
    playbackRate: {
      default: 1,
      options: [0.5, 0.75, 1, 1.5, 2],
    },
    audio: {
      language: 'auto',
    },
    subtitles: {
      active: false,
      language: 'auto',
      native: false,
      useVttjs: false,
      timestampMap: true,
    },
    keyboardControl: true,
    allowDownload: false,
    fullscreen: {
      enabled: true,
      fallback: true,
      iosNative: false,
    },
    doubleclickFullscreen: true,
    menu: {
      loop: true,
      autoPlay: true,
      playbackRate: true,
      qualityLevels: true,
      audio: false,
      subtitles: false,
    },
    theatre: {
      enabled: true,
      width: '100%',
      height: '60%',
      marginTop: 0,
      horizontalAlign: 'center',
      keepPosition: false,
      advanced: false,
    },
    title: null,
    logo: {
      imageUrl: null,
      clickUrl: null,
      mouseOverImageUrl: null,
      width: '100px',
      height: '20px',
      position: 'top left',
      opacity: 1,
      imageMargin: '2px',
      hideWithControls: false,
    },
    controlBar: {
      autoHide: false,
      autoHideTimeout: 3,
      animated: true,
    },
    showTimeOnHover: true,
    timelinePreview: {
      file: '',
      spriteImage: false,
      spriteRelativePath: false,
    },
    htmlOnPauseBlock: {
      html: null,
      height: null,
      width: null,
    },
    layout: 'default',
    playerInitCallback: () => {},
    persistentSettings: {
      playbackRate: true,
      quality: true,
      volume: true,
      theatre: true,
    },
    controlForwardRewind: {
      show: false,
      forward: 10,
      rewind: 10,
    },
    contextMenu: {
      controls: true,
      links: [],
    },
  },
  captions: {
    play: 'Play',
    pause: 'Pause',
    mute: 'Mute',
    unmute: 'Unmute',
    subtitles: 'Subtitles',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit Fullscreen',
    shortcutsInfo: 'Keyboard Shortcuts',
  },
  onBeforeXMLHttpRequestOpen: (request) => {},
  onBeforeXMLHttpRequest: (request) => {},
  hls: {
    url: 'https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js',
    customUrl: '',
    debug: false,
    overrideNative: false,
    config: (options) => {
      return options;
    },
    onBeforeInit: (hls) => {},
    onAfterInit: (hls) => {},
  },
  dash: {
    url: 'https://cdn.dashjs.org/latest/dash.all.min.js',
    debug: false,
    config: (options) => {
      return options;
    },
    onBeforeInit: (dash) => {},
    onAfterInit: (dash) => {},
  },
  storage: {
    enabled: true,
    key: 'cvp',
    expiration: 30,
    shared: true,
  },
  debug: false,
  blankVideo: 'https://cdn.fluidplayer.com/static/blank.mp4',
  events: [
    // Events to watch on HTML5 media elements and bubble
    // https://developer.mozilla.org/en/docs/Web/Guide/Events/Media_events
    'ended',
    'progress',
    'stalled',
    'playing',
    'waiting',
    'canplay',
    'canplaythrough',
    'loadstart',
    'loadeddata',
    'loadedmetadata',
    'timeupdate',
    'volumechange',
    'play',
    'pause',
    'error',
    'seeking',
    'seeked',
    'emptied',
    'ratechange',
    'cuechange',

    // Custom events
    'userActive',
    'userInactive',
    'enterfullscreen',
    'exitfullscreen',
    'theatreModeOn',
    'theatreModeOff',
    'audiochange',
    'languagechange',
  ],
};

export default defaults;
