server {
    listen 80;
    server_name _;

    server_tokens off;
    absolute_redirect off;
    disable_symlinks on;
    root /usr/share/nginx/html;

    location = /v1/current/player.min.js {
        add_header Cache-Control "no-store" always;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        return 302 __CURRENT_LOCATION__;
    }

    location ~* "^/v1/deployments/[0-9]{8}T[0-9]{6}Z-(?:[a-f0-9]{8}|[a-f0-9]{32})/(?:sha256/[a-f0-9]{64}/)?[^/]+\.(?:js|svg|txt)$" {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=604800" always;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
